-- MySQL Script generated by MySQL Workbench
-- 01/09/19 11:48:18
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema interview
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `interviewee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `interviewee` ;

CREATE TABLE IF NOT EXISTS `interviewee` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `organization` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `video`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `video` ;

CREATE TABLE IF NOT EXISTS `video` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `filePath` VARCHAR(255) NOT NULL,
  `face` DOUBLE NULL,
  `affinity` DOUBLE NULL,
  `confidence` DOUBLE NULL,
  `stability` DOUBLE NULL,
  `expression` DOUBLE NULL,
  `autognosis` DOUBLE NULL,
  `applyPurpose` DOUBLE NULL,
  `interviewee_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_video_interviewee_idx` (`interviewee_id` ASC),
  CONSTRAINT `fk_video_interviewee`
    FOREIGN KEY (`interviewee_id`)
    REFERENCES `interviewee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
